# Generated by Django 2.2.6 on 2020-11-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 's_user',
                'managed': False,
            },
        ),
    ]
