# Generated by Django 2.2.6 on 2020-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RUserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('operate_type', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('operation_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_user_record',
                'managed': False,
            },
        ),
    ]
