# Generated by Django 2.2 on 2022-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rPatientRtms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('treatment_id', models.IntegerField()),
                ('resting_motor_threshold', models.IntegerField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('treatment_num', models.IntegerField(blank=True, null=True)),
                ('times_per_day', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=40, null=True)),
                ('doctor_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete', models.IntegerField()),
            ],
            options={
                'db_table': 'r_patient_rtms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tTreatmentRtms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('treatment_id', models.IntegerField()),
                ('treatment_name', models.CharField(max_length=40)),
                ('therapeutic_target', models.CharField(blank=True, max_length=40, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('pulses', models.IntegerField(blank=True, null=True)),
                ('stimulation_time', models.IntegerField(blank=True, null=True)),
                ('inter_train_intervals', models.IntegerField(blank=True, null=True)),
                ('pulse_trains', models.IntegerField(blank=True, null=True)),
                ('total_pulses', models.IntegerField(blank=True, null=True)),
                ('total_time_minute', models.IntegerField(blank=True, null=True)),
                ('total_time_second', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=40, null=True)),
                ('doctor_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete', models.IntegerField()),
            ],
            options={
                'db_table': 't_treatment_rtms',
                'managed': False,
            },
        ),
    ]
