# Generated by Django 2.2.6 on 2020-11-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RPatientBasicInformationHealth',
        ),
    ]
