# Generated by Django 2.2.6 on 2020-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_delete_rpatientbasicinformationhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPatientBasicInformationHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_somatic_diseases', models.IntegerField(blank=True, null=True)),
                ('patient_somatic_diseases_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_somatic_diseases_year', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_mental_diseases', models.IntegerField(blank=True, null=True)),
                ('patient_mental_diseases_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_mental_diseases_year', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_family_diseases_history', models.IntegerField(blank=True, null=True)),
                ('patient_family_diseases_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_medicine_information', models.TextField()),
                ('patient_treatment_information', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'r_patient_basic_information_health',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RPatientSembu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_school', models.DateField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('mark_level', models.IntegerField(blank=True, null=True)),
                ('parents_status', models.IntegerField(blank=True, null=True)),
                ('question1_father', models.IntegerField(blank=True, null=True)),
                ('question1_mother', models.IntegerField(blank=True, null=True)),
                ('question2_father', models.IntegerField(blank=True, null=True)),
                ('question2_mother', models.IntegerField(blank=True, null=True)),
                ('question3_father', models.IntegerField(blank=True, null=True)),
                ('question3_mother', models.IntegerField(blank=True, null=True)),
                ('question4_father', models.IntegerField(blank=True, null=True)),
                ('question4_mother', models.IntegerField(blank=True, null=True)),
                ('question5_father', models.IntegerField(blank=True, null=True)),
                ('question5_mother', models.IntegerField(blank=True, null=True)),
                ('question6_father', models.IntegerField(blank=True, null=True)),
                ('question6_mother', models.IntegerField(blank=True, null=True)),
                ('question7_father', models.IntegerField(blank=True, null=True)),
                ('question7_mother', models.IntegerField(blank=True, null=True)),
                ('question8_father', models.IntegerField(blank=True, null=True)),
                ('question8_mother', models.IntegerField(blank=True, null=True)),
                ('question9_father', models.IntegerField(blank=True, null=True)),
                ('question9_mother', models.IntegerField(blank=True, null=True)),
                ('question10_father', models.IntegerField(blank=True, null=True)),
                ('question10_mother', models.IntegerField(blank=True, null=True)),
                ('question11_father', models.IntegerField(blank=True, null=True)),
                ('question11_mother', models.IntegerField(blank=True, null=True)),
                ('question12_father', models.IntegerField(blank=True, null=True)),
                ('question12_mother', models.IntegerField(blank=True, null=True)),
                ('question13_father', models.IntegerField(blank=True, null=True)),
                ('question13_mother', models.IntegerField(blank=True, null=True)),
                ('question14_father', models.IntegerField(blank=True, null=True)),
                ('question14_mother', models.IntegerField(blank=True, null=True)),
                ('question15_father', models.IntegerField(blank=True, null=True)),
                ('question15_mother', models.IntegerField(blank=True, null=True)),
                ('question16_father', models.IntegerField(blank=True, null=True)),
                ('question16_mother', models.IntegerField(blank=True, null=True)),
                ('question17_father', models.IntegerField(blank=True, null=True)),
                ('question17_mother', models.IntegerField(blank=True, null=True)),
                ('question18_father', models.IntegerField(blank=True, null=True)),
                ('question18_mother', models.IntegerField(blank=True, null=True)),
                ('question19_father', models.IntegerField(blank=True, null=True)),
                ('question19_mother', models.IntegerField(blank=True, null=True)),
                ('question20_father', models.IntegerField(blank=True, null=True)),
                ('question20_mother', models.IntegerField(blank=True, null=True)),
                ('question21_father', models.IntegerField(blank=True, null=True)),
                ('question21_mother', models.IntegerField(blank=True, null=True)),
                ('refusal_mother', models.FloatField(blank=True, null=True)),
                ('refusal_father', models.FloatField(blank=True, null=True)),
                ('emotional_warmth_mother', models.FloatField(blank=True, null=True)),
                ('emotional_warmth_father', models.FloatField(blank=True, null=True)),
                ('overprotection_mother', models.FloatField(blank=True, null=True)),
                ('overprotection_father', models.FloatField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'r_patient_sembu',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BPatientAppointment',
        ),
        migrations.DeleteModel(
            name='BPatientBaseInfo',
        ),
        migrations.DeleteModel(
            name='DPatientAppointment',
        ),
        migrations.DeleteModel(
            name='DPatientDetail',
        ),
        migrations.DeleteModel(
            name='RUserRecord',
        ),
        migrations.DeleteModel(
            name='SUser',
        ),
    ]
