# Generated by Django 2.2 on 2021-01-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_auto_20201217_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RPatientInclusionExclusionCriteria',
        ),
        migrations.DeleteModel(
            name='RPatientInformedConsentSignaturePage',
        ),
        migrations.DeleteModel(
            name='RPatientMriSafetyQuestionnaire',
        ),
    ]
