# Generated by Django 2.2.6 on 2021-01-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0004_rselftestduration'),
        ('scales', '0004_auto_20210120_1031'),
    ]

    operations = [
    ]
