
# Generated by Django 2.2 on 2021-03-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_merge_20210127_1043'),
        ('scales', '0005_merge_20210128_1438'),
    ]

    operations = [
    ]
