# Generated by Django 2.2 on 2021-07-14 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0007_rpatientgad_rpatientinsomnia_rpatientphq_rpatientpss'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPatientSuicideBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suicide_action', models.IntegerField(blank=True, null=True)),
                ('suicide_times', models.CharField(blank=True, max_length=45, null=True)),
                ('self_harming', models.IntegerField(blank=True, null=True)),
                ('self_harming_times', models.CharField(blank=True, max_length=45, null=True)),
                ('suicide_idea', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'r_patient_suicide_behavior',
                'managed': False,
            },
        ),
    ]
