# Generated by Django 2.2 on 2022-05-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_session_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('standard_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('is_urgent', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('item_type', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('create_time', models.BigIntegerField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_schedule',
                'managed': False,
            },
        ),
    ]
