# Generated by Django 2.2.6 on 2020-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_bpatientbaseinfo_dpatientdetail_dscales_rpatientbasicinformationabuse_rpatientbasicinformationfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEthnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'd_ethnicity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DPatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('pre_diagnosis', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_patient_appointment',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BPatientAppointment',
        ),
        migrations.DeleteModel(
            name='DScales',
        ),
        migrations.DeleteModel(
            name='RPatientBasicInformationAbuse',
        ),
        migrations.DeleteModel(
            name='RPatientBasicInformationFamily',
        ),
        migrations.DeleteModel(
            name='RPatientBasicInformationHealth',
        ),
        migrations.DeleteModel(
            name='RPatientBasicInformationOther',
        ),
        migrations.DeleteModel(
            name='RPatientBasicInformationStudy',
        ),
    ]
