# Generated by Django 2.2 on 2021-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20201217_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPatientGhr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghr_id', models.IntegerField()),
                ('patient_session_id', models.IntegerField(blank=True, null=True)),
                ('diagnosis', models.IntegerField(blank=True, null=True)),
                ('kinship', models.IntegerField(blank=True, null=True)),
                ('doctor_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'r_patient_ghr',
                'managed': False,
            },
        ),
    ]
