# Generated by Django 2.2 on 2021-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rpatientblood'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPatientIsMedicalAdvice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_medical_advice', models.IntegerField(blank=True, null=True)),
                ('medical_advice_path', models.CharField(blank=True, max_length=50, null=True)),
                ('ma_create_time', models.DateTimeField(blank=True, null=True)),
                ('ma_update_time', models.DateTimeField(blank=True, null=True)),
                ('is_progress_note', models.IntegerField(blank=True, null=True)),
                ('progress_note_path', models.CharField(blank=True, max_length=50, null=True)),
                ('pn_create_time', models.DateTimeField(auto_now_add=True)),
                ('pn_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'd_patient_is_medical_advice',
                'managed': False,
            },
        ),
    ]
