# Generated by Django 2.2 on 2021-10-29 20:51

from django.db import migrations, models
import tools.Utils


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rpatientblood'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPatientMedicalAdviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('medical_name', models.CharField(blank=True, max_length=40, null=True)),
                ('dose_num', models.FloatField(blank=True, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('drug_type', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('usage_way', models.CharField(blank=True, max_length=20, null=True)),
                ('start_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('start_nurse', models.CharField(blank=True, max_length=20, null=True)),
                ('end_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('end_nurse', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'b_patient_medical_advice_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DPatientIsMedicalAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('is_medical_advice', models.IntegerField(blank=True, null=True)),
                ('medical_advice_path', models.FileField(upload_to=tools.Utils.get_patient_medical_advice_direct)),
                ('ma_create_time', models.DateTimeField(blank=True, null=True)),
                ('ma_update_time', models.DateTimeField(blank=True, null=True)),
                ('is_progress_note', models.IntegerField(blank=True, null=True)),
                ('progress_note_path', models.FileField(upload_to=tools.Utils.get_patient_progress_note_direct)),
                ('pn_create_time', models.DateTimeField(blank=True, null=True)),
                ('pn_update_time', models.DateTimeField(blank=True, null=True)),
                ('postscript', models.CharField(blank=True, max_length=400, null=True)),
                ('is_postscript', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_patient_is_medical_advice',
                'managed': False,
            },
        ),
    ]
