# Generated by Django 2.2 on 2021-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_dpatientismedicaladvice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPatientMedicalAdviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('medical_name', models.CharField(blank=True, max_length=40, null=True)),
                ('dose_num', models.FloatField(blank=True, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('drug_type', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('usage_way', models.CharField(blank=True, max_length=20, null=True)),
                ('start_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('start_nurse', models.CharField(blank=True, max_length=20, null=True)),
                ('end_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('end_nurse', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'b_patient_medical_advice_detail',
                'managed': False,
            },
        ),
    ]
